apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-micro-app-deployment
  labels:
    app: attendance-micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-micro-app
  template:
    metadata:
      labels:
        app: attendance-micro-app 
    spec:
      containers:
      - name: attendance-micro-app
        image: asandro/attendance_micro_github
        env:
        - name: MONGO_URI
          value: "specify MONGO_URI environemnt variable here"
        - name: JWT_SECRET
          value: "specify JWT_SECRET environemnt variable here"
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"



