apiVersion: v1
kind: Service
metadata:
  name: attendance-micro-app-service
spec:
  selector:
    app: attendance-micro-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 31110