apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-micro-app-deployment
  labels:
    app: db-micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-micro-app
  template:
    metadata:
      labels:
        app: db-micro-app 
    spec:
      containers:
      - name: db-micro-app
        image: asandro/db_micro_github
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"