apiVersion: v1
kind: Service
metadata:
  name: db-micro-app-service
spec:
  selector:
    app: db-micro-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 31130